[build]
  publish = "bluehorizon"
  command = ""

[[redirects]]
  from = "/comments"
  to = "/comments/index.html"
  status = 200

[[redirects]]
  from = "/blogs"
  to = "/blogs/index.html"
  status = 200
